added company structure documentation
front-commerce/developers.front-commerce.com pull request #273
Opened 2021-12-03 16:37 UTC by mo-fc

2021-12-03 16:49 UTC, abailleulfc requested changes

2021-12-03 16:49 UTC, abailleulfc commented on source/docs/appendices/migration-guides.md
> +The company structure link is added to the `<AccountNavigation>` component. This link is part of the B2B features so if you need it you need it and have overridden `<AccountNavigation>` component you
```suggestion
The company structure link is added to the `<AccountNavigation>` component. This link is part of the B2B features so if you need it and overrode the `<AccountNavigation>` component you need to apply [the same changes in this diff to your overridden `<AccountNavigation>`](https://gitlab.com/front-commerce/front-commerce/-/merge_requests/802/diffs#diff-content-e7af65f5100c0e8b1d5bda98a735eb5744a44386)
```

2021-12-17 10:17 UTC, paul-vd approved these changes

2021-12-20 08:44 UTC, dpobel commented on source/docs/appendices/migration-guides.md
> +```
to remove ?

2021-12-20 08:44 UTC, dpobel commented on source/docs/appendices/migration-guides.md
> +
empty line

2021-12-20 09:34 UTC, merged