document RMA
front-commerce/developers.front-commerce.com pull request #311
Opened 2022-01-28 12:33 UTC by mo-fc

2022-01-28 14:19 UTC, abailleulfc requested changes

2022-01-28 14:19 UTC, abailleulfc commented on source/docs/advanced/features/return-merchandise-authorization.md
> +Return Merchandise Authorization (RMA) provides a customer with the means to request a return of an order or part of an order. In Front Commerce we provide a base platform agnostice module to support
```suggestion
Return Merchandise Authorization (RMA) provides a customer with the means to request a return of an order or part of an order. In Front Commerce we provide a base platform agnostic module to support RMA. We also ship some platform specific implementations for RMA (so far we have an implementation for Magento1 Enterprise). It is up to the integrator to either use one of our provided implementations that suits his platform. Or extend our base RMA module to add functionality to his specific platform.
```

2022-01-28 14:19 UTC, abailleulfc commented on source/docs/advanced/features/return-merchandise-authorization.md
> +The base RMA module is located at `src/server/modules/front-commerce/rma` it contains the basic GraphQL schema and empty resolver implementation. This module is all you need to know what is required
```suggestion
The base RMA module is located at `src/server/modules/front-commerce/rma` it contains the basic GraphQL schema and empty resolver implementation. This module is all you need to know what is required to implement an RMA module that supports your platform.
```

2022-01-31 14:08 UTC, dpobel commented on source/docs/advanced/features/return-merchandise-authorization.md
> +We ship a page that is used to create a RMA. This page is located on `/user/orders/{orderId}/returns/create` you can link to this page to make the user create an RMA for a specific order. This page i
```suggestion
We ship a page that is used to create a RMA. The link to this page will show up in the order details page after you have implemented resolvers related to RMA.
```

2022-01-31 14:08 UTC, dpobel commented on source/docs/advanced/features/return-merchandise-authorization.md
> +All you need to do to implement an RMA that suits you is provide the server implementation needed for your specific platform/case. Having a look at Front Commerce's implementation of the Magento1 Ent
```suggestion
To implement a RMA for a new platfom, you have to provide the server implementation of the Graph. Having a look at Front-Commerce's implementation for Magento1 Enterprise RMA (`src/server/modules/magento1ee/rma`) should help give you some guidance. Here is a short summary of what is needed:
```

2022-01-31 14:08 UTC, dpobel commented on source/docs/advanced/features/return-merchandise-authorization.md
> +1. Extend the `ReturnMerchandiseAuthorizationStatus` enum with all the possible statuses that an RMA could have.
```suggestion
1. Extend the `ReturnMerchandiseAuthorizationStatus` enum with all the possible statuses that a RMA could have.
```

2022-01-31 14:08 UTC, dpobel commented on source/docs/advanced/features/return-merchandise-authorization.md
> +2. Extend the `ReturnedItemStatus` enum with all the possible statuses an returned item can have.
```suggestion
2. Extend the `ReturnedItemStatus` enum with all the possible statuses a returned item can have.
```

2022-02-02 11:07 UTC, merged