Document Payment method label translation key change
front-commerce/developers.front-commerce.com pull request #365
Opened 2022-03-23 10:34 UTC by mo-fc

2022-03-23 11:24 UTC, Kagaminara approved these changes
Lgtm !

2022-03-23 12:13 UTC, real34 requested changes
It is not clear for integrators that the PaymentLabel component has been relocated too.

Changing translation keys is wrong if they've overriden it. I think we must document the component relocation and mention the translation key update as a consequence.

2022-03-24 15:56 UTC, abailleulfc requested changes

2022-03-24 15:56 UTC, abailleulfc commented on source/docs/appendices/migration-guides.md
> +The `<PaymentMethodLabel>` component was moved from `theme/modules/User/Order/OrderMethod/PaymentMethodLabel.js` to `theme/modules/Checkout/Payment/PaymentMethodLabel.js` the old location will still
```suggestion
The `<PaymentMethodLabel>` component was moved from `theme/modules/User/Order/OrderMethod/PaymentMethodLabel.js` to `theme/modules/Checkout/Payment/PaymentMethodLabel.js` the old location will still work but will output deprecation messages when used. If you have overriden `<PaymentMethodLabel>` you should also relocate your override to the same path and update all references to point to it.
```

2022-03-25 06:11 UTC, real34 approved these changes

2022-03-25 10:00 UTC, merged