cloud-v2: configuration tips for deployments
front-commerce/developers.front-commerce.com pull request #383
Opened 2022-04-11 09:38 UTC by abailleulfc

Improve the configuration to provide simple configurations for logging and sessions based on the environment variable for the CloudV2

2022-04-11 09:45 UTC, mo-fc requested changes

2022-04-11 09:45 UTC, mo-fc commented on source/docs/advanced/production-ready/logging.md
> +You can also automate the logging configuration based on wether the application is deployed on our cloud offer (V2) or not using the following `my-module/config/logging.js`
```suggestion
You can also automate the logging configuration based on whether the application is deployed on our cloud offer (V2) or not using the following `my-module/config/logging.js`
```

2022-04-11 09:45 UTC, mo-fc commented on source/docs/advanced/production-ready/logging.md
> +    ? { type: "console" }
a little explanation of why they should use console in the cloud V2 will be helpful

2022-04-11 09:51 UTC, abailleulfc commented on source/docs/advanced/production-ready/logging.md
> +    ? { type: "console" }
on the cloud V2 we stream the logs to the standard output to then gather and exploit them in another platform

2022-04-12 17:10 UTC, real34 approved these changes

2022-04-13 06:38 UTC, merged