chore(prismic): add NullContent documentation
front-commerce/developers.front-commerce.com pull request #428
Opened 2022-07-21 10:03 UTC by paul-vd

2022-07-25 09:24 UTC, abailleulfc commented on source/docs/prismic/resolver-cache.md
> +The `NullContent` has been introduced to allow caching of resolvers that return `null`, lets say that you return a tag based on an id, but you only want to return the tags which are in the allow list
split in two sentences : the feature and the example
```suggestion
The `NullContent` has been introduced to allow caching of resolvers that return `null`.

Lets say that you return a tag based on an id, but you only want to return the tags which are in the allow list, in this case, we will return `null` for the tags that are not in the allow list.
```

2022-07-25 09:24 UTC, abailleulfc commented on source/docs/prismic/resolver-cache.md
> +The issue we will have here is that there is no way creating a reference to the Tag document in prismic, so we won't be able to know that `tag3` or `tag4` should cache `null`, so we introduced the Nu
```suggestion
The issue we have here is that there is no way to create a reference to the Tag document in prismic, so we won't be able to know that `tag3` or `tag4` should cache `null`.

The NullContent handles this.
```

2022-07-25 09:24 UTC, abailleulfc commented on source/docs/prismic/resolver-cache.md
> +```
I would say the most important here is the difference with the first code sample
```suggestion
```diff
import NullContent from "prismic/server/domain/NullContent";

const allowList = ["tag1", "tag2"];

export default {
  Query: {
    tag: PrismicCachedResolver((parent, args, { loaders }) => {
      const tag = loaders.TagLoader.loadById(args.id);
-      return allowList.includes(tag.name) ? tag : null;
+      return allowList.includes(tag.name) ? tag : NullContent(tag);
    }),
  },
};
```
```

2022-07-25 09:24 UTC, abailleulfc commented on source/docs/prismic/resolver-cache.md
> +```
same here (either remove the allowList or add also the import) I would go for the smaller solution
```suggestion
...
export default {
  Fax: {
    tag: PrismicCachedResolver((parent, args, { loaders }) => {
      const tag = loaders.DocumentLoader.loadTagByDocumentID(
        source.documentMetadata.documentID
      );
      return allowList.includes(tag.name)
        ? tag
        : NullContent(source.documentMetadata.documentID);
    }),
  },
};
```
```

2022-07-25 12:49 UTC, abailleulfc requested changes

2022-07-25 12:49 UTC, abailleulfc commented on source/docs/prismic/resolver-cache.md
> +
oh the diff didn't keep the closing backquotes

2022-07-25 12:49 UTC, abailleulfc commented on source/docs/prismic/resolver-cache.md
> +
same here, the diff didn't keep the closing backquotes

2022-08-01 11:56 UTC, paul-vd commented
closed in favor of https://github.com/front-commerce/developers.front-commerce.com/pull/431 which includes these changes

2022-08-01 11:56 UTC, closed without merging