chore(bigcommerce): add documentation related to cache webhooks
front-commerce/developers.front-commerce.com pull request #429
Opened 2022-07-21 14:47 UTC by paul-vd

2022-07-21 14:48 UTC, paul-vd commented
FC-1032

2022-07-21 15:07 UTC, Kagaminara reviewed
few nits

2022-07-22 15:32 UTC, paul-vd commented on source/docs/bigcommerce/webhooks.md
> +Thats all, you should now be ready to recieve webhooks on your application using your webhook secret.
lmao... there were other points when I wrote that line 🙃 hehehe

2022-07-25 09:15 UTC, abailleulfc requested changes

2022-07-25 09:15 UTC, abailleulfc commented on source/docs/bigcommerce/webhooks.md
> +First you will need to create a webhook secret within your Front-Commerce app, to do this, you can add the `FRONT_COMMERCE_BIG_COMMERCE_WEBHOOK_SECRET` environment variable to your `.env` file.
```suggestion
You need to setup the webhook secret within your Front-Commerce app with the `FRONT_COMMERCE_BIG_COMMERCE_WEBHOOK_SECRET` environment variable.
```

Team "shorter is better" :sweat_smile:

2022-07-25 09:15 UTC, abailleulfc commented on source/docs/bigcommerce/webhooks.md
> +1. Copy the `API path` as it contains the `Store Hash`. (see figure below)
Why not putting the store hash image just under this point ?

2022-07-25 09:15 UTC, abailleulfc commented on source/docs/bigcommerce/webhooks.md
> +To do this we first need to setup Authentication for your BigCommerce account, you can refer to the [documentation](https://developer.bigcommerce.com/docs/ZG9jOjIyMDYxMw-v2-and-v3-rest-api-authentica
```suggestion
We first need to setup Authentication for your BigCommerce account (you can refer to the [documentation](https://developer.bigcommerce.com/docs/ZG9jOjIyMDYxMw-v2-and-v3-rest-api-authentication)).
```
nitpick : just seems more readable like this :innocent:

2022-07-25 09:15 UTC, abailleulfc commented on source/docs/bigcommerce/webhooks.md
> +You are now ready to get started with your webhooks, we have created a [BigCommerce Webhook API](https://documenter.getpostman.com/view/16678499/UzQys4QZ) in postman to simplify this process, you can
```suggestion
You are now ready to get started with your webhooks, we have created a [BigCommerce Webhook API](https://documenter.getpostman.com/view/16678499/UzQys4QZ) in postman to simplify this process, you can hit the `Run in Postman` button and simply replace all the relevant variables to get started [creating your webhooks](#Creating-a-webhook).
```

2022-07-25 09:15 UTC, abailleulfc commented on source/docs/bigcommerce/webhooks.md
> +To update a webhook, you first need to run the `GET ALL WEBHOOKS` api, it will return an array of webhooks, you can then replace the `WEBHOOK_ID` variable with the id of the webhook that you want to
```suggestion
To update a webhook, you first need to run the `GET ALL WEBHOOKS` api to get an array of webhooks. You can then replace the `WEBHOOK_ID` variable with the id of the webhook that you want to remove.
```

2022-07-29 09:29 UTC, Kagaminara approved these changes

2022-07-29 16:01 UTC, real34 approved these changes

2022-07-29 16:01 UTC, real34 commented on source/docs/bigcommerce/webhooks.md
> +Thats all, you should now be ready to recieve webhooks on your application using your webhook secret.
```suggestion
Thats all, you should now be ready to receive webhooks on your application using your webhook secret.
```

2022-07-29 18:13 UTC, merged