fix: various typos, consistent capitalization and working anchors in external login doc
front-commerce/developers.front-commerce.com pull request #464
Opened 2022-09-09 13:01 UTC by dpobel

noticed while working on https://gitlab.com/front-commerce/front-commerce/-/merge_requests/1456

2022-09-09 13:10 UTC, dpobel commented on docs/advanced/features/external-logins/index.mdx
> +[Adding the necessary modules](#adding-the-necessary-modules) you need to ensure
actually anchors must now be in lowercase and we have a lot in the documentation… I'll open a different MR to fix others

2022-09-09 14:09 UTC, dpobel commented on docs/advanced/features/external-logins/index.mdx
> +[Adding the necessary modules](#adding-the-necessary-modules) you need to ensure
same fix done in the rest of the documentation in https://github.com/front-commerce/developers.front-commerce.com/pull/465

2022-09-12 07:56 UTC, abailleulfc requested changes

2022-09-12 07:56 UTC, abailleulfc commented on docs/advanced/features/external-logins/index.mdx
> +you are have the Magento1 connector on 1.4.2 or later.
```suggestion
you are required to have the Magento1 connector on 1.4.2 or later.
```
Maybe I did not guess the missing words right

2022-09-13 07:21 UTC, merged