Add node 18 compatibility
front-commerce/developers.front-commerce.com pull request #548
Opened 2022-11-30 11:09 UTC by Kagaminara

2022-12-01 15:19 UTC, paul-vd approved these changes

2022-12-01 15:19 UTC, paul-vd commented on docs/appendices/migration-guides/index.mdx
> +Starting version 2.20, Front-Commerce officially supports Node 18. However, as
```suggestion
Starting from version 2.20, Front-Commerce officially supports Node 18. However, as
```

or even

```suggestion
Front-Commerce officially supports Node 18 starting from version 2.20. However, as
```

2022-12-02 15:18 UTC, Kagaminara commented on docs/appendices/migration-guides/index.mdx
> +`NODE_OPTIONS=--openssl-legacy-provider npm run build`.
I added a snippet, tell me what you think about it :)

2022-12-05 12:25 UTC, paul-vd requested changes

2022-12-05 12:25 UTC, paul-vd commented on docs/appendices/migration-guides/index.mdx
> +```
This can be removed once https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/merge_requests/1743 is merged.

2022-12-06 12:00 UTC, real34 requested changes
To be reworked. The only needed change might in fact be https://developers.front-commerce.com/docs/appendices/release-notes

2022-12-06 12:12 UTC, Kagaminara commented
> To be reworked. The only needed change might in fact be https://developers.front-commerce.com/docs/appendices/release-notes

Yes, that was my conclusion too.

2022-12-06 19:17 UTC, real34 approved these changes

2022-12-07 08:19 UTC, merged