chore: add graphql playground documentation
front-commerce/developers.front-commerce.com pull request #655
Opened 2023-05-10 09:13 UTC by paul-vd

### What?
This adds the documentation to create a playground in an remix application

2023-05-10 14:08 UTC, real34 requested changes

2023-05-10 14:08 UTC, real34 commented on docs/api-reference/front-commerce-remix/graphql-playground.mdx
> +variable to `production`
**issue:** this isn't correct. We don't allow it in production, and don't recommend it.

**suggestion:** 
```suggestion
## Playground in a staging environment

The playground must not be enabled in a production environment. However, it is useful in staging environments. To enable it in a production build you need to set the `FRONT_COMMERCE_ENV` environment
variable to `dev`. The application will start as usual, but you could access the playground to query your live GraphQL server.
```

2023-05-12 07:39 UTC, real34 approved these changes

2023-05-12 11:49 UTC, Kagaminara approved these changes

2023-05-12 15:19 UTC, merged