Merge branch 'main' into next
front-commerce/developers.front-commerce.com pull request #798
Opened 2023-10-16 13:55 UTC by paul-vd

## What?
This updates the `Your first route` documentation to follow the example of `hello-world.tsx` provided in the skeleton. It also includes examples of how to load data from the unified graphql schema.

## Preview
- TODO link

2023-10-17 07:36 UTC, real34 commented
**issue:** there are several incorrect things regarding this patch

> This updates the Your first route documentation to follow the example of hello-world.tsx provided in the skeleton. It also includes examples of how to load data from the unified graphql schema.

This is not correct. The issue was about adding a new page : "Get Started > Loading data from Front-Commerce's unified GraphQL schema"

The "Your first route" was already good enough for its goal.

Also, the example in the "advanced" route with fetching isn't realistic. The goal is to reproduce the same patterns that developers will find in FC. In the current state it isn't really close to what's in the core:
- in FC the query is loaded from `~/graphql/graphql`
- in FC we always have metas
- it could in fact (that wasn't in acceptance criteria) be better to show a page with a param (e.g: `:id`) that would allow us to show how to do error management (404)

The `_main.wishlist.share.$shareCode.($path).($itemId).tsx` route could be used as an inspiration for the most common patterns developers will see on a "dynamic page" that fetches data from GraphQL.

2023-10-17 07:36 UTC, real34 requested changes
**issue:** there are several incorrect things regarding this patch

> This updates the Your first route documentation to follow the example of hello-world.tsx provided in the skeleton. It also includes examples of how to load data from the unified graphql schema.

This is not correct. The issue was about adding a new page : "Get Started > Loading data from Front-Commerce's unified GraphQL schema"

The "Your first route" was already good enough for its goal.

Also, the example in the "advanced" route with fetching isn't realistic. The goal is to reproduce the same patterns that developers will find in FC. In the current state it isn't really close to what's in the core:
- in FC the query is loaded from `~/graphql/graphql`
- in FC we always have metas
- it could in fact (that wasn't in acceptance criteria) be better to show a page with a param (e.g: `:id`) that would allow us to show how to do error management (404)

The `_main.wishlist.share.$shareCode.($path).($itemId).tsx` route could be used as an inspiration for the most common patterns developers will see on a "dynamic page" that fetches data from GraphQL.

2024-01-08 13:33 UTC, real34 commented on docs/01-get-started/loading-data-from-unified-graphql-schema.mdx
> +  using Remix. This guide delves into the practical aspects of querying and
**nitpick:** the sentence isn't very clear that it's about the app's unified schema exposed by FC

**suggestion:**

```suggestion
  Explore how to retrieve dynamic data from your application's unified GraphQL schema in a Front-Commerce route
  using Remix. This guide delves into the practical aspects of querying and
```

2024-01-08 13:35 UTC, real34 commented on docs/01-get-started/loading-data-from-unified-graphql-schema.mdx
> +  [Remix routes](https://remix.run/docs/en/main/discussion/routes)
**nitpick:** I think it's better to link to our own content explaining the previous steps

**suggestion:** replace the link with our how-to guide explaining routes basics (it itself links to further official / advanced resources)

```suggestion
- Basic knowledge of
  [Remix routes](/docs/3.x/get-started/your-first-route)
```

2024-01-08 13:37 UTC, real34 commented on docs/01-get-started/loading-data-from-unified-graphql-schema.mdx
> +  installed and configured
**nitpick:** this is only useful for using the code as is

**suggestion:** 

```suggestion
- [FAQ GraphQL Module](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/tree/c317ab057ae0927e294a5287eb8e0be73ca7e1fb/skeleton/extensions/faq-demo/graphql)
  installed and configured if you want to execute code samples without any changes
```

2024-01-08 13:39 UTC, real34 commented on docs/01-get-started/loading-data-from-unified-graphql-schema.mdx
> +};
**issue:** this is part of the "Loading data" section which is incorrect

**suggestion:** create another "Mutate data" section explaining that same concepts seen for loading data can be used for mutating data

2024-01-08 13:42 UTC, real34 commented on docs/01-get-started/loading-data-from-unified-graphql-schema.mdx
> +Front-Commerce and Remix.
```suggestion
As we can see here retrieving dynamic data from Front-Commerce unified GraphQL schema 
can be done in a natural way from any route. But this only scratches the surface of what you can do with
Front-Commerce and Remix.
```

2024-01-09 08:33 UTC, Kagaminara approved these changes
LGTM

2024-01-09 09:15 UTC, real34 approved these changes

2024-01-09 09:15 UTC, real34 commented on docs/01-get-started/loading-data-from-unified-graphql-schema.mdx
> +renders it using a <FaqDetail /> Page component (that is a plain React
**issue:** the component is interpreted

![2024-01-09_10-15](https://github.com/front-commerce/developers.front-commerce.com/assets/75968/e23eb35b-02ff-4bfa-8f33-baf5d6c40957)

**suggestion:** 

```suggestion
renders it using a `<FaqDetail />` Page component (that is a plain React
```

2024-01-09 09:54 UTC, merged