Added migration guide about theme chocolatine style refactor
front-commerce/developers.front-commerce.com pull request #854
Opened 2024-03-04 12:53 UTC by Kagaminara

This MR documents a forgotten migration guide following [FC-1802](https://linear.app/front-commerce/issue/FC-1802/styles-typography-fonts-etc-import-from-a-location-making-sense).

2024-03-04 13:16 UTC, paul-vd requested changes

2024-03-04 13:16 UTC, paul-vd commented on docs/100-upgrade/migration-guides/3.2-3.3.mdx
> +application, as detailed below **or copy the ones from the latest skeleton**.
This is only true if integrators have overwritten the `main.scss`,

```suggestion
In this release, we refactored how the design tokens are included in the style sheets. They are now included through the [`_design-tokens.scss`](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/blob/main/packages/theme-chocolatine/theme/_design-tokens.scss)
`_design-tokens.scss` file. <br /> I you have overwritten the [`theme/main.scss` ](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/blob/main/packages/theme-chocolatine/theme/main.scss#L3) then you should apply this changes to your overrides, by either applying the patch as detailed below or [copy the file from the latest skeleton](https://gitlab.blackswift.cloud/front-commerce/front-commerce/-/blob/main/packages/theme-chocolatine/theme/main.scss).
```

2024-03-04 13:17 UTC, paul-vd commented on docs/100-upgrade/migration-guides/3.2-3.3.mdx
> +```
Also update suggestion from : https://github.com/front-commerce/developers.front-commerce.com/pull/854#discussion_r1511140138 accordingly

2024-03-04 15:03 UTC, Kagaminara commented on docs/100-upgrade/migration-guides/3.2-3.3.mdx
> +</details>
Applied this eventually, and also updated the text above this description.

2024-03-05 09:31 UTC, paul-vd approved these changes
Some nitpicking, but looks good

2024-03-05 09:32 UTC, Kagaminara commented on docs/100-upgrade/migration-guides/3.2-3.3.mdx
> +```
Oopsie

2024-03-05 09:32 UTC, paul-vd approved these changes

2024-03-05 09:32 UTC, paul-vd commented on docs/100-upgrade/migration-guides/3.2-3.3.mdx
> +
Remove this space

```suggestion
```

2024-03-05 10:26 UTC, merged