docs: Documented the list of environment variables used by Contentful extension
front-commerce/developers.front-commerce.com pull request #891
Opened 2024-04-26 08:41 UTC by Kagaminara

This MR refactors the "Reference" section of our Contentful doc to feature a new "Environment variables" section for listing all variables used by the Contentful extension.

[Preview ](https://deploy-preview-891--heuristic-almeida-1a1f35.netlify.app/docs/3.x/extensions/contentful/reference/environment-variables)

2024-04-26 16:39 UTC, paul-vd requested changes
This deserves a url redirect

- OLD: https://deploy-preview-891--heuristic-almeida-1a1f35.netlify.app/docs/3.x/extensions/contentful/reference -> 
- NEW: https://deploy-preview-891--heuristic-almeida-1a1f35.netlify.app/docs/3.x/extensions/contentful/reference/api

2024-04-26 16:39 UTC, real34 approved these changes

2024-04-29 06:57 UTC, Kagaminara commented
> This deserves a url redirect
> 
> * OLD: https://deploy-preview-891--heuristic-almeida-1a1f35.netlify.app/docs/3.x/extensions/contentful/reference ->
> * NEW: https://deploy-preview-891--heuristic-almeida-1a1f35.netlify.app/docs/3.x/extensions/contentful/reference/api
> 
> see https://github.com/front-commerce/developers.front-commerce.com/blob/main/static/_redirects

I added the redirect.

2024-04-29 07:28 UTC, paul-vd approved these changes

2024-04-29 08:56 UTC, merged